### PR TITLE
Add more data to outputs (e.g. self-links)

### PR DESCRIPTION
**Pull request by rolyv**
Adding self-links for master, private, and public agents, as well as private and public agent IPs. This makes it easier to build on top of the DCOS installation (for example: GCP Global LoadBalancer, authorized IPs for Cloud SQL database). 

Depends on https://github.com/dcos-terraform/terraform-gcp-infrastructure/pull/10

### CODE REVIEW

**Comment by rolyv** [comment]
@bernadinm Can you please review?

**Review by bernadinm — DISMISSED** [review]
LGTM @fatz since our three major providers, AWS, GCP and Azure have the same outputs and since we are leveraging a main.tf with custom outputs calling the `dcos` module block directly, this should be a good solution change to to add any meaningful outputs to the dcos module internally as the end users using the main.tf outputs will not change.

If so, we can also do the same for our other cloud providers.

**Review by fatz — DISMISSED** [review]
I agree. My intention in the past was to keep the outputs as small as possible to not overwhelm users. 

However I absolutely see the benefit of this. So yeah lets merge and try to port this into aws and azure. 

@bernadinm can you take care of this process? Also it should be cherry-picked / merged into v0.2

**Comment by fatz** [comment]
@rolyv could you please set the minimum version for the infrastructure module to 0.1.2?

with that we tag the infrastructure module and merge this

**Comment by rolyv** [comment]
Done. Thanks

**Review by bernadinm — DISMISSED** [review]

**Pull request closed without merging**
